name: Release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  prepare:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-11, windows-2022]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - name: Cache dependencies
        uses: actions/cache@v2
        env:
          cache-name: cache-cargo
        with:
          path: ~/.cargo/registry
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - name: Build
        run: cargo build --release
      - uses: actions/upload-artifact@v3
        with:
          name: release-binary-${{ runner.os }}
          path: target/release/french-numbers*
  
  release:
    needs: [prepare]
    runs-on: ubuntu-latest
    steps:
      - name: Download Linux artifact
        uses: actions/download-artifact@v3
        with:
          name: release-binary-Linux
          path: linux
      - name: Download macOS artifact
        uses: actions/download-artifact@v3
        with:
          name: release-binary-macOS
          path: macos
      - name: Download Windows artifact
        uses: actions/download-artifact@v3
        with:
          name: release-binary-Windows
          path: windows
      - name: Compress Linux binary
        working-directory: linux
        run: tar -czf french-numbers-linux.tar.gz french-numbers
      - name: Compress macOS binary
        working-directory: macos
        run: tar -czf french-numbers-macOS.tar.gz french-numbers
      - name: Compress Windows binary
        working-directory: windows
        run: zip -9 french-numbers-windows.zip french-numbers.exe
      - uses: softprops/action-gh-release@v1
        with:
          files: |
            linux/french-numbers-linux.tar.gz
            macos/french-numbers-macOS.tar.gz
            windows/french-numbers-windows.zip
